# Generated by Django 4.0.4 on 2022-04-21 14:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAlbum', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('puntuacion', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_Musical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreGrupo', models.CharField(max_length=50)),
                ('estiloMusica', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField()),
                ('fecha_disolucion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('duracion', models.TimeField()),
                ('generoCancion', models.CharField(max_length=50)),
                ('album_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.album')),
                ('artista_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.artista')),
            ],
        ),
        migrations.AddField(
            model_name='artista',
            name='grupo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.grupo_musical'),
        ),
        migrations.AddField(
            model_name='album',
            name='artista_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.artista'),
        ),
        migrations.AddField(
            model_name='album',
            name='grupoMusical_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.grupo_musical'),
        ),
    ]
