# Generated by Django 4.0.4 on 2022-04-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0002_alter_album_artista_id_alter_album_grupomusical_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='anio',
            field=models.IntegerField(default=0),
        ),
    ]
